name: sync-fork-daily-once
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: { }
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - run: |
          gh repo sync $REPOSITORY -b $BRANCH_NAME \
            --source $SOURCE_REPOSITORY \
            --skip '.github/workflows/**'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SOURCE_REPOSITORY: ${{ github.event.repository.parent.full_name }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}
